### ISSUE TITLE
4. Testing Posts

### ISSUE THREAD

**Issue by lvreynoso** [MakeSchool-Tutorials/Node-Reddit-Clone#20]
On this page about testing, the test for creating a new post uses the `/posts` route, but in the previous pages the router we created for a POST request for new posts, and the new post form, use `/posts/new` as the route.

Also it would probably be a good idea to explicitly show that in this test file you need to import the `db.js` file that was created for the database connection - otherwise those calls to `Post.find()`, etc. do nothing.

**Comment by droxey** [comment]
Thanks @lvreynoso for your helpful contribution!

This has been fixed and will roll out with the next deployment late tonight. 👍
