### ISSUE TITLE
2. Create a Post - Connecting Your Database Typo

### ISSUE THREAD

**Issue by timkaing** [MakeSchool-Tutorials/Node-Reddit-Clone#21]
When requiring the database in the **server.js** file, require **reddit-db** instead to match the **reddit-db.js** file we made previously in the tutorial. 

```javascript
// Set db
require('./data/reddit-clone-db');
```

to 

````javascript
// Set db
require('./data/reddit-db');
````

**Comment by fchikwekwe** [comment]
I ran into this issue as well.

**Comment by droxey** [comment]
Thanks @fchikwekwe and @TkRain23 for your helpful contribution!

This has been fixed and will roll out with the next deployment late tonight. 👍
