### ISSUE TITLE
11. Comments on Comments: Part Deux

### ISSUE THREAD

**Issue by jaebooker** [MakeSchool-Tutorials/Node-Reddit-Clone#25]
When I run this, it says CommentSchema is undefined.

const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const CommentSchema = new Schema({
  content: { type: String, required: true },
  comments: [CommentSchema]
});

module.exports = mongoose.model("Comment", CommentSchema);

I tried using [this], but that seemed to bring in its own problems later on, when trying to run post.comments.id(req.params.commentId), claiming comments did not have a 'function'.

app.post("/posts/:postId/comments/:commentId/replies", (req, res) => {
  // LOOKUP THE PARENT POST
  Post.findById(req.params.postId)
    .then(post => {
      // FIND THE CHILD COMMENT
      var comment = post.comments.id(req.params.commentId);
      // ADD THE REPLY
      comment.comments.unshift(req.body);
      // SAVE THE CHANGE TO THE PARENT DOCUMENT
      return post.save();
    })
    .then(post => {
      // REDIRECT TO THE PARENT POST#SHOW ROUTE
      res.redirect("/posts/" + post._id);
    })
    .catch(err => {
      console.log(err.message);
    });
});

**Comment by droxey** [comment]
Thanks for your helpful contribution @jaebooker. I added some additional text regarding embedding strategies and some handy links to documentation regarding embedded documents in MongoDB. 👍
