### ISSUE TITLE
1. User Narratives, Wire Frames, and Technical Planning

### ISSUE THREAD

**Issue by campbellmarianna** [MakeSchool-Tutorials/Node-Reddit-Clone#28]
On the section titled "Technical Planning" the initial list of steps says "Associate posts, comments, and votes with the author" where as the solution only says "Associate posts and comments with the author", it is missing votes.

**Comment by ibirnam** [comment]
nice catch! fixed in 4946c430fc51da56751edebb6c0fca161d9ddeaf
