### ISSUE TITLE
4. Testing Posts

### ISSUE THREAD

**Issue by campbellmarianna** [MakeSchool-Tutorials/Node-Reddit-Clone#29]
In the section titled Testing /Posts/Create, the code snippet has an extra comma:
```
const newPost = {
      title: 'post title',
      url: 'https://www.google.com',
      summary: 'post summary',
  };
```
Furthermore, the pseudocode below it has a typo:
" // How many posts are there now?
// Make a request to create another
// Check that the database has one more post in it
// Check that the response is a successful "

It seems that the fourth comment doesn't need the "a".

**Comment by ibirnam** [comment]
Great catch! Fixed now in 00dfa67c5df38e8aa70fdeceaf62808a9c3d3c9b
