### ISSUE TITLE
10. Comments on Comments

### ISSUE THREAD

**Issue by mediassumani** [MakeSchool-Tutorials/Node-Reddit-Clone#31]
I can't see the part where we have to add a property in the Comment model "comments" to hold other comments. Creates an error when i do comment.comments.unshift(reply._id)

**Comment by ibirnam** [comment]
Oh man, sorry about that! Missed including that step in that chapter. Resolved in f8825c7a6b118fb74f41a8aefb3f027256439948 and will be updated live on the tutorial in the next few minutes
