### ISSUE TITLE
2. Create a Post

### ISSUE THREAD

**Issue by Nyapal** [MakeSchool-Tutorials/Node-Reddit-Clone#33]
Please explain the bug you found here.

when you do npm install express-validator version 6 is installed & app.use(expressValidator()); no longer works :( 

i just installed an earlier version of express-validator (^5.3.1) bc i couldn't figure out the fix

**Comment by ibirnam** [comment]
@Nyapal - great catch with this! It looks like this is indeed broken with [6.x versions of express-validator](https://github.com/express-validator/express-validator/issues/735)

Until we figure out a migration plan, I updated the tutorial to install the 5.x version and a brief explanation as to why we're doing that. Thanks again!

**Comment by Adamkaram** [comment]
so can we now use app.use(expressValidator())?
