### ISSUE TITLE
6. Comment on Posts

### ISSUE THREAD

**Issue by Beck-Haywood** [MakeSchool-Tutorials/Node-Reddit-Clone#34]
Update your SHOW call in your posts controller to be the following:

// LOOK UP THE POST
Post.findById(req.params.id).populate('comments').then((post) => {
  res.render('post-show.hbs', { post })
}).catch((err) => {
  console.log(err.message)
})

This line has one type and .hbs is not nessesary.
Correct version:
res.render('posts-show', { post })

**Comment by ibirnam** [comment]
great catch @Beck-Haywood ! Tutorial has been updated!
