### ISSUE TITLE
9. Testing Authentication

### ISSUE THREAD

**Issue by teknofage** [MakeSchool-Tutorials/Node-Reddit-Clone#36]
the posts/new test was failing because i had a post/new route

there were console logs in places there should not have been, like auth.js

there was no instruction to import the User in test/posts.js

the subreddit field needs to be added to the describe function on test/posts.js

**Comment by ibirnam** [comment]
@teknofage - this should be fixed now! We just did a big revamp of the tutorial, let us know if you run into any issues!
