### ISSUE TITLE
SUBMIT THE FORM: req.body is undefined

### ISSUE THREAD

**Issue by LucHighwalker** [MakeSchool-Tutorials/Node-Reddit-Clone#5]
Express is apparently no longer bundled with middleware such as the body-parser. You need to install the body-parser separately through npm, and call it via the post call. Like so:

```
const bodyParser = require('body-parser');

urlEncodedParser = bodyParser.urlencoded({extended: false});
app.post('/posts/new', urlEncodedParser, (req, res) => {
    console.log(req.body);
});
```

**Comment by droxey** [comment]
This is covered in P01-Create-A-Post, closing!
